# Generated by Django 2.2.5 on 2020-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201208_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconstraints',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labgroup',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otherconstraints',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='theorygroup',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
