# Generated by Django 2.2.5 on 2020-12-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201208_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
