# Generated by Django 2.2.5 on 2020-10-11 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 16, 16, 949530, tzinfo=utc)),
        ),
    ]
