# Generated by Django 2.2.5 on 2020-10-11 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_page_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 38, 49, 876913, tzinfo=utc)),
        ),
    ]
